export type AssetType = 'character' | 'environment' | 'projectile' | 'effect' | 'ui' | 'audio';
export type AssetStatus = 'placeholder' | 'polished_prototype' | 'final';
export type AssetSourceType = 'repository_owned' | 'generated_in_project' | 'licensed' | 'unknown';

export type AssetManifestEntry = {
  readonly id: string;
  readonly type: AssetType;
  readonly status: AssetStatus;
  readonly sourceType: AssetSourceType;
  readonly sourceNote: string;
  readonly assetKey: string;
  readonly fallbackKey?: string;
};

const generated = (
  id: string,
  type: AssetType,
  assetKey: string,
  fallbackKey?: string
): AssetManifestEntry => ({
  id,
  type,
  status: 'polished_prototype',
  sourceType: 'generated_in_project',
  sourceNote: 'Repository-owned Phaser Graphics texture generated by PreloadScene.',
  assetKey,
  fallbackKey
});

export const CHARACTER_ASSET_IDS = [
  'player', 'office_worker', 'phone_user', 'jogger', 'umbrella_pedestrian', 'delivery_rider',
  'dog_walker', 'cleaner', 'angry_pedestrian', 'camera_pedestrian', 'streamer', 'tourist',
  'security_guard', 'boss_influencer'
] as const;

export const PROJECTILE_ASSET_IDS = [
  'normal_poop', 'sticky_poop', 'splash_poop', 'jumbo_poop',
  'bouncy_poop', 'stink_poop', 'split_poop', 'golden_poop'
] as const;

export const ASSET_MANIFEST: readonly AssetManifestEntry[] = [
  generated('character_fallback', 'character', 'character-fallback'),
  ...CHARACTER_ASSET_IDS.map((id) => generated(`character_${id}`, 'character', `character-${id}`, 'character-fallback')),
  generated('projectile_fallback', 'projectile', 'projectile-fallback'),
  ...PROJECTILE_ASSET_IDS.map((id) => generated(`projectile_${id}`, 'projectile', `projectile-${id}`, 'projectile-fallback')),
  generated('environment_city', 'environment', 'environment-city-tile'),
  generated('environment_rooftop', 'environment', 'environment-rooftop-tile'),
  generated('effect_spark', 'effect', 'effect-spark'),
  generated('effect_smoke', 'effect', 'effect-smoke'),
  generated('ui_panel', 'ui', 'ui-panel'),
  generated('ui_icon_fallback', 'ui', 'ui-icon-fallback'),
  {
    id: 'audio_generated_bank', type: 'audio', status: 'polished_prototype', sourceType: 'generated_in_project',
    sourceNote: 'WebAudio oscillator/noise cues synthesized at runtime; no external recording.', assetKey: 'audio-generated-bank'
  }
] as const;

export function assetByKey(assetKey: string): AssetManifestEntry | undefined {
  return ASSET_MANIFEST.find((entry) => entry.assetKey === assetKey);
}
